services:
  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file: ../.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - qdrant

  worker:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    command: ["uv", "run", "celery", "-A", "app.main.celery_app", "worker", "-l", "INFO"]
    env_file: ../.env
    depends_on:
      - redis
      - postgres
      - qdrant

  flower:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:v1.11.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  postgres_data:
  qdrant_storage:
