"""add prices table

Revision ID: 1341a353937f
Revises: f274e7ea9f79
Create Date: 2025-09-08 21:26:34.441765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1341a353937f'
down_revision: Union[str, None] = 'f274e7ea9f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'ts', name='uq_price_symbol_ts')
    )
    op.create_index('ix_price_symbol_ts', 'prices', ['symbol', 'ts'], unique=False)
    op.create_index(op.f('ix_prices_symbol'), 'prices', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_symbol'), table_name='prices')
    op.drop_index('ix_price_symbol_ts', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
