"""add_usd_balance_to_users

Revision ID: f4a3d8b9c123_add_usd_balance
Revises: f30eed726612_add_new_position_fields
Create Date: 2025-10-02 14:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4a3d8b9c123_add_usd_balance'
down_revision = 'f30eed726612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usd_balance', sa.Numeric(precision=20, scale=8), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usd_balance')
    # ### end Alembic commands ###

