"""add_new_position_fields

Revision ID: f30eed726612
Revises: 81f19f28661b
Create Date: 2025-09-16 00:37:25.770197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30eed726612'
down_revision: Union[str, None] = '81f19f28661b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('buy_price', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('positions', sa.Column('buy_date', sa.Date(), nullable=True))
    op.add_column('positions', sa.Column('currency', sa.String(), nullable=False, server_default='USD'))
    op.add_column('positions', sa.Column('account', sa.String(), nullable=True))
    op.alter_column('positions', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=8),
               existing_nullable=False)
    op.drop_column('positions', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('positions', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('positions', 'account')
    op.drop_column('positions', 'currency')
    op.drop_column('positions', 'buy_date')
    op.drop_column('positions', 'buy_price')
    # ### end Alembic commands ###
