name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pipx install uv
      - name: Install deps
        working-directory: backend
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -r requirements.txt
      - name: Lint & Test
        run: |
          backend/.venv/bin/ruff check backend
          backend/.venv/bin/pytest -q
